### ISSUE TITLE
Using XInput.Enabled = true always disables XInput

### ISSUE THREAD

**Issue by bennybroseph** [BlindEyeSoftworks/BlindEye.XInput#1]
I could be wrong, but I believe this property is incorrect.
```
public static bool Enabled
{
    get { return inputEnabled; }
    set
    {
        inputEnabled = value;
        Enable(false);
    }
}
```
When setting XInput to be enabled or disabled it instead is always set to be disabled. I was confused the first time using the code base provided as I couldn't get it to work for awhile until I changed the above to:
```
public static bool Enabled
{
    get { return inputEnabled; }
    set
    {
        inputEnabled = value;
        Enable(inputEnabled);
    }
}
```
which I think was the original intention of the property.

**Comment by BL1NDX3N0N** [comment]
Thank you for your submission. The issue has been corrected, closed, and marked as resolved.
