### ISSUE TITLE
[Feature Request] Support for Impulse Triggers, and Elite's extra buttons and/or profiles

### ISSUE THREAD

**Issue by Paliverse** [BlindEyeSoftworks/BlindEye.XInput#2]
So far this little xinput wrapper is amazing! Beyond impressed that i can confidently add native xbox support within my application. Just hope the above can be added as i bought special elite controllers to test out the functionality. I may be speaking too soon as i haven't tried everything yet with the elites.

**Comment by BL1NDX3N0N** [comment]
Hey there, I am extremely happy to hear your enjoyment! I am very sorry for the late response, I wasn't notified.

To answer your question, haptics such as on the Xbox One controllers are not supported by the drivers used by Xbox 360 peripherals nor does the XInput or DirectInput APIs define functionality for interacting with those motors either. That functionality right now is only present in the GameInput API which is available in Microsoft's GDK and the binaries required for such should be pre-installed in Windows 10 and later. Given this is an XInput wrapper/binding, it wouldn't really fit into it and I made certain to include that in the [documentation](https://github.com/BlindEyeSoftworks/BlindEye.XInput/blob/main/src/XInput/Features.cs#L25) as well for updating [Microsoft's documentation](https://learn.microsoft.com/en-us/windows/win32/xinput/xinput-game-controller-apis-portal).

If targeting UWP it is worth checking out the [Windows.Gaming.Input](https://learn.microsoft.com/en-us/uwp/api/windows.gaming.input.gamepadvibration?view=winrt-22621) namespace which should wrap everything in the GameInput API. Another key point of the GameInput API is that it supports modern controllers with haptics as well for being compatible with older versions of Windows and XInput peripherals.

Cheers and happy holidays!
